### ISSUE TITLE
include "how to run this notebook" instructions

### ISSUE THREAD

**Issue by Joshdpaul** [ua-snap/ardac-notebooks#13]
Its easy to forget how the "shift+enter" thing is unknown to non-notebook users. Consider including this instruction at the head of every notebook, or in a standalone readme file (eg "How to use these notebooks.md")

**Comment by charparr** [comment]
Added instructions to the head of each notebook for running single cells, all cells, and downloading the notebook in an .ipynb file. Linked out to Jupyter project page.
